api_version: v1
kind: Agent
metadata:
  name: echo-agent
  display_name: Echo Agent
  description: A simple echo agent that repeats your voice
  avatar_url: ""
  instructions: |
    You are a simple echo agent that repeats what the user says.
    Just echo back their voice without any processing.
spec:
  worker:
    name: echo-agent
    type: echo-agent
  input:
    audio:
      sample_rate: 48000
      channels: 1
  output:
    audio:
      sample_rate: 48000
      channels: 1 