version: '3.8'

services:
  livekit:
    image: livekit/livekit-server:latest
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    environment:
      - LIVEKIT_KEYS=devkey:secret
    volumes:
      - ./livekit.yaml:/livekit.yaml
    command: --config /livekit.yaml
    restart: unless-stopped

volumes:
  livekit-data:
