system_prompt: |
  You are a first-class, polite, and very fast AI sales assistant...
response_format_instruction: |
  Your response MUST be in JSON format...
summarization_prompt: |
  You are an expert in text compression. Summarize the following dialogue...
